apiVersion: v1
kind: Service
metadata:
  name: conure
  labels:
    app.kubernetes.io/name: conuredb
spec:
  selector:
    app.kubernetes.io/name: conuredb
    role: voter
  ports:
    - name: http
      port: {{ .Values.service.httpPort }}
      targetPort: {{ .Values.service.httpPort }} 